"""inicial schema ai

Revision ID: 27d66edb1468
Revises:
Create Date: 2026-08-14 09:47:49.871008

"""

from __future__ import annotations

import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

revision = "27d66edb1468"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_evaluations",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("execution_id", sa.String(length=36), nullable=False),
        sa.Column("evaluator", sa.String(length=20), nullable=False),
        sa.Column("metric", sa.String(length=50), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_evaluations")),
        schema="ai",
    )
    op.create_index(
        "ix_agent_evaluations_execution_id",
        "agent_evaluations",
        ["execution_id"],
        unique=False,
        schema="ai",
    )
    op.create_table(
        "agent_executions",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("thread_id", sa.String(length=36), nullable=True),
        sa.Column("agent_type_id", sa.String(length=36), nullable=False),
        sa.Column("version_id", sa.String(length=36), nullable=True),
        sa.Column("agent_instance_id", sa.String(length=36), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("input", sa.JSON(), nullable=True),
        sa.Column("output", sa.JSON(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_executions")),
        schema="ai",
    )
    op.create_index(
        "ix_agent_executions_agent_type_id_created_at",
        "agent_executions",
        ["agent_type_id", "created_at"],
        unique=False,
        schema="ai",
    )
    op.create_index(
        "ix_agent_executions_thread_id",
        "agent_executions",
        ["thread_id"],
        unique=False,
        schema="ai",
    )
    op.create_table(
        "agent_experiences",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("agent_type_id", sa.String(length=36), nullable=False),
        sa.Column("version_id", sa.String(length=36), nullable=True),
        sa.Column("trigger_pattern", sa.Text(), nullable=False),
        sa.Column("response_pattern", sa.Text(), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("success_rating", sa.Float(), nullable=False),
        sa.Column("recurrence_count", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_experiences")),
        schema="ai",
    )
    op.create_index(
        "ix_agent_experiences_agent_type_id",
        "agent_experiences",
        ["agent_type_id"],
        unique=False,
        schema="ai",
    )
    op.create_table(
        "agent_feedback",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("execution_id", sa.String(length=36), nullable=True),
        sa.Column("thread_id", sa.String(length=36), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_feedback")),
        schema="ai",
    )
    op.create_index(
        "ix_agent_feedback_created_at", "agent_feedback", ["created_at"], unique=False, schema="ai"
    )
    op.create_index(
        "ix_agent_feedback_execution_id",
        "agent_feedback",
        ["execution_id"],
        unique=False,
        schema="ai",
    )
    op.create_table(
        "agent_memories",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("agent_instance_id", sa.String(length=36), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("agent_type_id", sa.String(length=36), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_memories")),
        schema="ai",
    )
    op.create_index(
        "ix_agent_memories_agent_instance_id",
        "agent_memories",
        ["agent_instance_id"],
        unique=False,
        schema="ai",
    )
    op.create_index(
        "ix_agent_memories_user_id_agent_type_id",
        "agent_memories",
        ["user_id", "agent_type_id"],
        unique=False,
        schema="ai",
    )
    op.create_table(
        "agent_runtime_configs",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("agent_type_id", sa.String(length=36), nullable=False),
        sa.Column("version_id", sa.String(length=36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runtime_configs")),
        sa.UniqueConstraint("agent_type_id", name="uq_agent_runtime_configs_agent_type_id"),
        schema="ai",
    )
    op.create_table(
        "knowledge_chunks",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("knowledge_base_id", sa.String(length=36), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_chunks")),
        schema="ai",
    )
    op.create_index(
        "ix_knowledge_chunks_document_id",
        "knowledge_chunks",
        ["document_id"],
        unique=False,
        schema="ai",
    )
    op.create_index(
        "ix_knowledge_chunks_knowledge_base_id",
        "knowledge_chunks",
        ["knowledge_base_id"],
        unique=False,
        schema="ai",
    )
    # Índice vectorial HNSW (pgvector) para búsqueda semántica en la recuperación RAG.
    op.execute(
        "CREATE INDEX ix_knowledge_chunks_embedding_hnsw "
        "ON ai.knowledge_chunks USING hnsw (embedding vector_cosine_ops)"
    )
    op.create_table(
        "threads",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("agent_type_id", sa.String(length=36), nullable=False),
        sa.Column("agent_instance_id", sa.String(length=36), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_threads")),
        schema="ai",
    )
    op.create_index(
        "ix_threads_agent_instance_id", "threads", ["agent_instance_id"], unique=False, schema="ai"
    )
    op.create_index("ix_threads_user_id", "threads", ["user_id"], unique=False, schema="ai")
    op.create_table(
        "messages",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("thread_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tool_calls", sa.JSON(), nullable=True),
        sa.Column("tool_results", sa.JSON(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["ai.threads.id"],
            name=op.f("fk_messages_thread_id_threads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        schema="ai",
    )
    op.create_index(
        "ix_messages_thread_id_created_at",
        "messages",
        ["thread_id", "created_at"],
        unique=False,
        schema="ai",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_messages_thread_id_created_at", table_name="messages", schema="ai")
    op.drop_table("messages", schema="ai")
    op.drop_index("ix_threads_user_id", table_name="threads", schema="ai")
    op.drop_index("ix_threads_agent_instance_id", table_name="threads", schema="ai")
    op.drop_table("threads", schema="ai")
    op.drop_index(
        "ix_knowledge_chunks_knowledge_base_id", table_name="knowledge_chunks", schema="ai"
    )
    op.drop_index("ix_knowledge_chunks_document_id", table_name="knowledge_chunks", schema="ai")
    op.execute("DROP INDEX ai.ix_knowledge_chunks_embedding_hnsw")
    op.drop_table("knowledge_chunks", schema="ai")
    op.drop_table("agent_runtime_configs", schema="ai")
    op.drop_index(
        "ix_agent_memories_user_id_agent_type_id", table_name="agent_memories", schema="ai"
    )
    op.drop_index("ix_agent_memories_agent_instance_id", table_name="agent_memories", schema="ai")
    op.drop_table("agent_memories", schema="ai")
    op.drop_index("ix_agent_feedback_execution_id", table_name="agent_feedback", schema="ai")
    op.drop_index("ix_agent_feedback_created_at", table_name="agent_feedback", schema="ai")
    op.drop_table("agent_feedback", schema="ai")
    op.drop_index("ix_agent_experiences_agent_type_id", table_name="agent_experiences", schema="ai")
    op.drop_table("agent_experiences", schema="ai")
    op.drop_index("ix_agent_executions_thread_id", table_name="agent_executions", schema="ai")
    op.drop_index(
        "ix_agent_executions_agent_type_id_created_at", table_name="agent_executions", schema="ai"
    )
    op.drop_table("agent_executions", schema="ai")
    op.drop_index("ix_agent_evaluations_execution_id", table_name="agent_evaluations", schema="ai")
    op.drop_table("agent_evaluations", schema="ai")
    # ### end Alembic commands ###
